[package]
name = "rust_backend"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_backend"
crate_type = ["cdylib", "rlib"]

[dependencies]
fltk = "^1.4"

palette = "0.7.2"
image = "0.24.6"
pyo3 = {version = "0.19.2", features = ["extension-module"]}