[package]
name = "LVIE-GPU"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "LVIE-GPU"
path = "src/main.rs"

[dependencies]
bytemuck = "1.9"
image = "0.24"
pollster = "0.2"
wgpu = "0.14"